### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by anushkanz** [alagafonov/php-trademe-jobs-api#1]
Hi
Fatal error: Uncaught Error: Class 'Client' not found in /index.php:5 Stack trace: #0 {main} thrown in /index.php on line 5
Any idea

**Comment by anushkanz** [comment]
Fatal error: Uncaught InvalidArgumentException: A relative URI must not have a path beginning with a segment containing a colon in /Applications/XAMPP/xamppfiles/htdocs/tm/vendor/guzzlehttp/psr7/src/Uri.php:798 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/tm/vendor/guzzlehttp/psr7/src/Uri.php(547): GuzzleHttp\Psr7\Uri->validateState() #1 /Applications/XAMPP/xamppfiles/htdocs/tm/vendor/alagafonov/php-trademe-jobs-api/lib/Trademe/HttpClient/Plugins/AddApiUrl.php(30): GuzzleHttp\Psr7\Uri->withPath('https://api.tra...') #2 /Applications/XAMPP/xamppfiles/htdocs/tm/vendor/php-http/client-common/src/PluginClient.php(161): Trademe\HttpClient\Plugins\AddApiUrl->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure)) #3 /Applications/XAMPP/xamppfiles/htdocs/tm/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request)) #4 /Applications/XAMPP/xamppfiles/htdocs/tm/vendor/php-http/client-common/src/PluginClient in /Applications/XAMPP/xamppfiles/htdocs/tm/vendor/guzzlehttp/psr7/src/Uri.php on line 798
